version: '2'

services:
  proxy:
    image: traefik
    command: --web --docker --docker.domain=dh.grafolab.org --logLevel=DEBUG
    networks:
      - dhunica
      - dhomekas
      - whois
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/traefik.toml
      - ./acme.json:/etc/traefik/acme.json

networks:
  dhunica:
    external:
      name: dhunica_default
  dhomekas:
    external:
      name: dh.unica_omeka.s
  whois:
    external:
      name: whoiam_default
